onlyBuiltDependencies:
  - lefthook

catalog:
  "@biomejs/biome": "2.3.7"
  "@commitlint/cli": "20.1.0"
  "@commitlint/config-conventional": "20.0.0"
  "@nivalis/biome-config": "2.3.7"
  "@total-typescript/ts-reset": "0.6.1"
  "@types/bun": "1.3.3"
  "@types/node": "22.2.0"
  "lefthook": "2.0.4"
  "typescript": "5.9.3"
  "zshy": "0.6.0"
