name: Check
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Check typescript
        run: bun run ts

      - name: Check eslint
        run: bun run lint

      - name: Check tests
        run: bun run test

      - name: Check build
        run: bun run build
